#!/bin/bash

# Function to check if a command exists
command_exists() {
    command -v "$@" > /dev/null 2>&1
}

# Function to check if a folder exists
folder_exists() {
    [ -d "$1" ] && return 0 || return 1
}

# Function to print formatted text in blue to represent information
fmt_info() {
    printf '%s\n' "${FMT_BOLD}${FMT_BLUE}" "$*" "$FMT_RESET"
}

# Function to print formatted text in green to represent success
fmt_success() {
    printf '%s\n' "${FMT_BOLD}${FMT_GREEN}" "$*" "$FMT_RESET"
}

# Function to pritn formatted text in red to represent errors
fmt_error() {
    printf '%s\n' "${FMT_BOLD}${FMT_RED}" "$*" "$FMT_RESET"
}

# Function to setup colors for the script messages 
setup_color() {
  # Using Catppuccin colors
  FMT_RED=$(printf '\033[38;2;243;139;168m')
  FMT_GREEN=$(printf '\033[38;2;166;227;161m')
  FMT_YELLOW=$(printf '\033[38;2;249;226;175m')
  FMT_BLUE=$(printf '\033[38;2;137;180;250m')
  FMT_BOLD=$(printf '\033[1m')
  FMT_RESET=$(printf '\033[0m')
}

# Function to verify minimum requirements for instalation
verify_requirements() {
    fmt_info "Verifying minimum requirements for installation..."
    if ! command_exists git; then
        fmt_error "Git is not installed. Please install git and try again."
        exit 1
    elif ! command_exists curl; then
        fmt_error "Curl is not installed. Please install curl and try again."
        exit 1
    fi
    fmt_success "Minimum requirements verified."
}

# Function to install Homebrew
install_brew() {
    if folder_exists "/home/linuxbrew/.linuxbrew"; then
        if command_exists brew; then
            if ! command_exists gcc; then
                post_install_brew
            fi
            fmt_info "Homebrew is already installed. Skipping installation..."
            return
        else
            eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
            if ! command_exists gcc; then
                post_install_brew
            fi
        fi
    else
        fmt_info "Installing Homebrew..."
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        post_install_brew
    fi
    fmt_success "Homebrew installed successfully."
    return
}

# Function to install essential packages of Homebrew
post_install_brew() {
    fmt_info "Homebrew installing essential packages..."
    brew install gcc

    if [ $? -eq 0 ]; then
        fmt_success "Essential packages installaed"
    else
        fmt_error "Failed to complete installation of essential packages. Exiting..."
        exit 1
    fi
}

# Function to install zsh
install_zsh() {
    if ! command_exists zsh; then
        fmt_info "Installing Zsh..."
        brew install zsh
        if [ $? -eq 0 ]; then
            fmt_success "Zsh installed successfully."
            return
        else
            fmt_error "Failed to install Zsh. Exiting..."
            exit 1
        fi
    else
        fmt_info "Zsh is already installed. Skipping installation..."
        return
    fi
    fmt_success "Zsh installed successfully."
    return
}

# Function to install Oh My Zsh
install_oh_my_zsh() {
    if folder_exists "$HOME/.oh-my-zsh"; then
        fmt_info "Oh My Zsh is already installed. Skipping installation..."
        return
    fi

    fmt_info "Installing Oh My Zsh..."

    yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    if [ $? -eq 0 ]; then
        fmt_success "Oh My Zsh installed successfully."
    else
        fmt_error "Failed to install Oh My Zsh. Exiting..."
        exit 1
    fi
}

# Function to install stow
install_stow() {
    if ! command_exists stow; then
        fmt_info "Installing Stow..."
        brew install stow
        if [ $? -eq 0 ]; then
            fmt_success "Stow installed successfully."
            return
        else
            fmt_error "Failed to install Stow. Exiting..."
            exit 1
        fi
    else
        fmt_info "Stow is already installed. Skipping installation..."
        return
    fi
    fmt_success "Stow installed successfully."
    return
}

# Main function to run the script
main() {
    # Line to setup colors to the terminal while running the script
    setup_color
    
    # Verify if the minimum requirements are met
    verify_requirements

    # Line just to ask the password to install the packages
    sudo -v
    
    # Check if Homebrew is installed and install it if not
    # Also install essential packages
    install_brew

    # Check if zsh is installed and install it if not
    install_zsh
    
    # Check if Oh My Zsh is instaled and install it if not
    install_oh_my_zsh

    # Check if stow is installed and install it if not
    install_stow
}

main